### ISSUE TITLE
Webpanel URL

### ISSUE THREAD

**Issue by shaikhnedab** [Summer-16/CSGO-VMP#1]
what is the url for webpanel?
sorry if it's a noob question.

**Comment by Summer-16** [comment]
Url for the panel will be the public IP of your server + port on which server is running
Example
if it's running on localhost (if your machine or server don't have public IP) then localhost:3535, for private IP 192.168.x.x:3535
if it's running on a server with public IP the your public IP x.x.x.x:3535

* you can change port in the config

**Comment by shaikhnedab** [comment]
yes figured it out. Thanks for your reply. going to test it tonight and will leave a feedback here for sure. Thanks again for releasing it for public.
